language: objective-c
xcode_workspace: e-guru.xcworkspace
osx_image: xcode10.1
podfile: i_CV_e-Guru_PROJ/Podfile
xcode_sdk: iphonesimulator12.1
xcode_scheme: e-guru
cache:
- cocoapods
  - bundler
before_install:
- pod install
env:
  global:
  - |
    - APP_NAME="e-Guru"
    - 'DEVELOPER_NAME="GTME_ProvProf_Dev"'
    - PROFILE_NAME="development-provisioning-profile"
  - secure: sktnyGXJs77ifVGOi6rIViRSgAWkTMTLIpPgmW++KKMRxNPlMNijCNzVrSp6A2MdZipD1grm4eteuL3YDHihV0KQD9MUPHuHpxroVwqvowNpNbRg+5q/gw/Tt3iykzGa9BXJkGm/lOhh+qu3KJ1QAp9ySncCEXhJY8e6uWYCgd77fHUi7qukbSop9SBWaERhuO0nSM6VSWB4tDW2OYnvCxHn+qBQvAWcC3RqjW+WMVXGlp9ATD6e3zPrRNMnwr/42q7fAJp66zKGuUpBdBTz302fGNrk/EMNfEaGnGd9CLYoIMANpgCOfYyT6aAB/+F+GJp7iXUwey7K6VvYAK88x+ZUPmZXNI3PLQamjnTQ91hfTDRpBdpJNTYHyfcR7wyC8aTYF8gs/khh++8bjHr2Ld6hJAMHDN0FmW+MMabMzYN3D+Fvg+sMjp+QRh/7330lOz5ywZoG6XocapmrF7wCGwfGttXw25lpMlQNDbdO7PZ8oSkG2OndAMNfh/M9l2zSMckt39D5mYrtNq2B+E/nd2r4viDjxdjdkLpjKf8VfnbVAxjjGhSP2d53ztzeE4muGrIg/yDL9lqGfqQunfI1Lqu5fvFjBUeY+1setw7NBjhnwL6PfD8+542dZGzsHfZ6hv0O+9sSy9ZY+XpASxIIuhRIYaKkqoi0bE9msfGcCf8=
before_script:
- "./scripts/add-key.sh"
script:
- xcodebuild clean build -workspace e-guru.xcworkspace -scheme e-guru -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8,OS=12.1" ONLY_ACTIVE_ARCH=NO | xcpretty
before_install:
   - rvm use system
   - sudo gem install xcpretty
   - sudo gem install cocoapods
